version: "3"
services:
    messenger:
        build: .
        environment:
            REDIS_HOST: redis
        command: python manage.py runserver 0.0.0.0:8002
        ports:
            - 8002:8002
        depends_on:
            - redis

    redis:
        image: redis:alpine